# Generated by Django 3.0.5 on 2020-04-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_group_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
